name: docker_build

on:
  push:
    branches: ["main", "ian/wip"]

jobs:
  docker_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ianrichardferguson/dev-ops-test:latest